import json
import re

import ollama

from guardrails import SecurityGuardrail
from rag_engine import RAGLogEngine
from schemas import AgentResponse
from tools import ToolRegistry


class GuardedToolAgent:
    def __init__(self, name: str, registry: ToolRegistry, model_name: str = "llama3"):
        self.name = name
        self.registry = registry
        self.model_name = model_name
        self.guardrail = SecurityGuardrail()
        self.rag_engine = RAGLogEngine()

    def _extract_json_object(self, raw_text: str):
        if not raw_text:
            return None

        stripped = raw_text.strip()
        if stripped.startswith("```"):
            stripped = re.sub(r"^```(?:json)?\s*", "", stripped)
            stripped = re.sub(r"\s*```$", "", stripped)

        start = stripped.find("{")
        end = stripped.rfind("}")
        if start != -1 and end != -1 and end > start:
            candidate = stripped[start : end + 1]
            try:
                return json.loads(candidate)
            except json.JSONDecodeError:
                pass

        try:
            return json.loads(stripped)
        except json.JSONDecodeError:
            return None

    def process(self, user_input: str, model_override: str = None) -> AgentResponse:
        active_model = model_override or self.model_name

        guardrail_result = self.guardrail.inspect_input(user_input)
        if guardrail_result["is_blocked"]:
            return AgentResponse(
                status="blocked",
                message=f"Input blocked by Guardrail: {guardrail_result['reason']}",
                tool_used=None,
                tool_output=None,
            )

        rag_results = self.rag_engine.query(user_input, k=3)
        context_str = "\n".join(rag_results) if rag_results else "No relevant security log records found."

        system_prompt = f"""You are an expert AI Security Operations Center (SOC) Analyst Agent.
Your job is to analyze the user's request plus retrieved log context and decide whether to execute a tool or provide a direct answer.

--- RETRIEVED SIEM LOG CONTEXT ---
{context_str}
----------------------------------

AVAILABLE REMEDIATION TOOLS:
1. `block_ip`: Block a malicious IP address on the firewall.
   - Arguments: {{"ip_address": "string (e.g. 192.168.1.105)", "reason": "string"}}
2. `restart_service`: Restart a system service (e.g. nginx, sshd).
   - Arguments: {{"service_name": "string", "force": boolean}}
3. `get_memory_usage`: Retrieve host RAM utilization metrics.
   - Arguments: {{"unit": "KB" | "MB" | "GB"}}

DECISION INSTRUCTIONS:
- If the query requests or requires a tool action, return ONLY a valid JSON object with the schema:
  {{"tool": "<tool_name>", "args": {{<argument_name>: <value>}}}}
- If no tool execution is required, provide a clear, concise SOC analysis.
- Return raw JSON only with no markdown fences.
"""

        try:
            response = ollama.chat(
                model=active_model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_input},
                ],
                options={"temperature": 0.1},
                format="json",
            )
            raw_output = response["message"]["content"].strip()
            tool_call = self._extract_json_object(raw_output)

            if isinstance(tool_call, dict) and "tool" in tool_call:
                tool_name = tool_call.get("tool")
                tool_args = tool_call.get("args", {}) or {}
                success, result, err = self.registry.execute_tool(tool_name, tool_args)

                if success:
                    return AgentResponse(
                        status="tool_execution",
                        message=f"Tool '{tool_name}' triggered via {active_model} reasoning.",
                        tool_used=tool_name,
                        tool_output=str(result),
                    )

                return AgentResponse(
                    status="error",
                    message=f"Schema validation or execution error for tool '{tool_name}': {err}",
                    tool_used=tool_name,
                    tool_output=None,
                )

            return AgentResponse(
                status="success",
                message=raw_output if raw_output else "No response generated by Ollama.",
                tool_used=None,
                tool_output=None,
            )

        except Exception as exc:
            return AgentResponse(
                status="error",
                message=f"Ollama connection error on model '{active_model}': {str(exc)}. Ensure 'ollama serve' is active.",
                tool_used=None,
                tool_output=None,
            )